/*global systemDictionary:true */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
'use strict';

systemDictionary = {
    "Alexa State": {                                  "en": "Alexa State of the List",                          "de": "Alexa Status der Liste",                           "ru": "Alexa Состояние списка",                           "pt": "Alexa Estado da Lista",                            "nl": "Alexa Staat van de lijst",                         "fr": "Alexa État de la liste",                           "it": "Stato dell'elenco di Alexa",                       "es": "Estado de la lista de Alexa",                      "pl": "Alexa Stan listy",                                 "uk": "Стан списку Alexa",                                "zh-cn": "列表中的 Alexa 状态"},
    "ID": {                                           "en": "ID of Alexa Device, state textCommand",            "de": "ID des Alexa-Geräts, Zustand textCommand",         "ru": "ID Alexa Device, состояние textCommand",           "pt": "ID do dispositivo Alexa, estado textCommand",      "nl": "ID van Alexa-apparaat, geef tekstopdracht aan",    "fr": "ID de l'appareil Alexa, indiquez textCommand",     "it": "ID del dispositivo Alexa, stato textCommand",      "es": "ID del dispositivo Alexa, comando de texto de estado", "pl": "ID urządzenia Alexa, stan textCommand",            "uk": "Ідентифікатор пристрою Alexa, стан textCommand",   "zh-cn": "Alexa 设备的 ID，状态 textCommand"},
};